### ISSUE TITLE
Taking the last card of a deck doesn't work

### ISSUE THREAD

**Issue by Sebaestschjin** [Sebaestschjin/gloomhaven-saveloader#10]
Taking cards from decks (e.g. attack modifiers cards or reward items) won't work if there's only 1 card left in the deck. This is due to the fact, that the deck doesn't exist anymore when there's only one card left. As a consequence loading a character with lots of perks or loading a save with all rewards won't work correctly.

**Comment by Seferan** [comment]
Sample JSON for testing:  https://pastebin.com/4yQe76ns
