### ISSUE TITLE
Quest cards from retired characters can not be saved

### ISSUE THREAD

**Issue by Sebaestschjin** [Sebaestschjin/gloomhaven-saveloader#12]
The section for retired characters also contains the name of the quest that character completed in order to retire. This is used to remove the quest from the deck of available quests, so no one else can do it again. However, this information isn't currently stored anywhere. So when later creating the save file this information is lost. This information is also not available when creating a save file from a game that never used to load feature in the first place. This wouldn't matter if it was possible to find out which quests are  still in the deck. But since the cards don't have names or description, the only clue would be the information of the custom object.
So the question is how to handle that case. Options I see:
* Ignore it, assuming that players know what quests are completed and will remove them on their own when they draw a duplicate quest.
* When loading the save, store the name of the quest somewhere, e.g. in the character name column, separated by a pipe. Then while saving this information can be retained. This would require players that create the save for the first time to input that information manually.
* Use the information in the custom object. This would be the URL to the steam image. Also I'm not sure, whether it's possible to distinguish between two quests cards, as they have the same image URL.

**Comment by Seferan** [comment]
Something that may help is CardID.  When a card exists in the world, it will have a CardID of a format similar to this:  199708.   It appears that the 08 part is an index in the "Image" file for which 
card to display.  Try grabbing the GUID of a few Quest Cards and dump this out:

log(getObjectFromGUID('fd72bf').getData().CardID)

I couldn't seem to see if I can get that value from a card while in the deck, but may be possible.   If we know the "index in the image file" (http://cloud-3.steamusercontent.com/ugc/938308629003295171/23633736004848E3B70239AEA286C08D15EB5961/) we should be able to get this figured out.

Finally, I have no idea how receptive the Mod Authors would be, but asking them to dump a Desc on the cards while in the deck would really improve things.

**Comment by Sebaestschjin** [comment]
Yeah, using the `CardId` does seems to work (see https://github.com/Sebaestschjin/gloomhaven-saveloader/commit/9a3677381e4798c642c1487cc2654698db98c56b). Im first checking whether the card comes from the correct Custom Deck (1997) and then use the index to identify the name of the Quest. The question would be, how fixed this Custom Deck ID is. It probably stays same unless the actual content changes, just have to make sure. :-)

I don't think you'd get that information of the card while in the deck itself, so I think putting all cards out, checking their content and putting the deck back together might be a good option.

Adding a  name or description to the cards would help be better, but would unfortunateley only work for future saves :-(.
