### ISSUE TITLE
Player scripting zones won't find single objects

### ISSUE THREAD

**Issue by Sebaestschjin** [Sebaestschjin/gloomhaven-saveloader#13]
The scripting zones for players won't find objects that lie directly on the table (via `getObjects()`). This is due to the fact that, their position is slightly too high. Reducing their y-positon by 0.01 to 4.22 solves the problem. Have to check with the original mod's authors to see if this is intended and if there would be any consequences to change that.
When this is not changed cards directly on the table can't be detected. This might apply to unequipped item cards or unequipped abilities which then can't be saved.

**Comment by Seferan** [comment]
The "Scenario Won" and "Scenario Lost" functionality likely have functionality that may help as it has to "reset" a lot of the cards when run

**Comment by Sebaestschjin** [comment]
They also just use `getObjects()`. Same for the Remove Player button. Which also won't work, if you have a card lying on the table. I changed that, so that before starting to save the game, the zones are slighly adjusted to `y=4.22`, which will find cards on the table and hopefully doesn't have other consequences. 🙃
