### ISSUE TITLE
Max HP Routine does not account for "Two-Minis"

### ISSUE THREAD

**Issue by Seferan** [Sebaestschjin/gloomhaven-saveloader#15]
The out of the box logic seems off right now as well, but may be fixed in future.  Regardless, the logic will need to include a search for the "Bear Companion" figure

object.tag = "Figurine"
object.getName() = "Bear Companion"
object.name = "Custom_Model")

**Comment by Sebaestschjin** [comment]
The out of box logic is "fixed" too, by simply adding a delay to the character loading. However doing this the right way will be done with #14 .
