### ISSUE TITLE
Handle invalid input gracefully

### ISSUE THREAD

**Issue by Sebaestschjin** [Sebaestschjin/gloomhaven-saveloader#23]
Currently if the input file contains invalid input (e.g. a class that doesn't exist or an item that can't be found) the loading process throws some error and all following loading steps are skipped.
It would be better to handle those kind of errors, issue a warning/error in the log and continue with the other steps. This way the loading would do as much as possible and hint of what didn't work aus as expected.

**Comment by Seferan** [comment]
A quick 'failure audit' that could be implemented is to have boolean flags set at the end of each major routine, then have a function (callable via console such as:  lua auditLoad()) and the function could spit out the flags.  Any flag not set would be suspect for failure.   

If/when the Task based system is implemented, this may go hand in hand with that.
