### ISSUE TITLE
Set the name of the Advanced Abilities after saving

### ISSUE THREAD

**Issue by Sebaestschjin** [Sebaestschjin/gloomhaven-saveloader#33]
To save the enhancements, the Advanced Ability deck is searched by name. Every card from the deck is drawn and thus the deck is destroyed. The save can't be done again because the Advanced Ability deck can't be found anymore. So after saving the enhancements and merging the abilities, the deck has to be named correctly again.

**Comment by Seferan** [comment]
Is the Advanced Ability deck search even necessary?  The only case in which I'd expect an enhanced card to be in this deck is if someone enhanced a character, retired, and then someone else is playing that character, but hasn't yet purchased the enhanced card.

I don't know how difficult the procedure is to "name the deck again" but an alternative may be to process half the deck, returning the cards, then processing the other half.  That way the deck never becomes empty.

**Comment by Seferan** [comment]
Also, may be possible to Save without drawing all the cards?   lua log(getObjectFromGUID('2264ab').getJSON()) appears to be returning information about each card which includes "AttachedDecals".

**Comment by Sebaestschjin** [comment]
Yeah, it's definitively a rare case and currently only possible through manual work. As you would carry over the enhancement information from a save file from a retired character to a new save file by hand, when the class is used again. However I still think this should work if done manually.

Naming the deck again shouldn't be that hard I guess, I'm thinking of a wait condition, that uses a cast at the deck position until an object is hit, that has the Deck tag and then sets its names. Maybe the performance is very poor than (as the doc suggest using cast very rarely). Doing the process for half the deck sound like a good plan for that! This would also get rid of the special case, where there's only one card left in the deck and you have to use the remainder card. Always a good thing to have less special cases. :-)

The use of the JSON also sounds promising. I hate that you have to draw cards from the deck to get their actual objects, so this might be a very good way to get the information without doing it.

**Comment by Sebaestschjin** [comment]
The function `getData()` was the way to go. It returns the information from `getJSON()` but already converts them into Lua tables. I wrapped that into a `DeckUtil` module, so that you can use the returned objects like other objects (e.g. using `getName()` or `getPosition()`.
