### ISSUE TITLE
Encode/Encrypt Hidden Notes

### ISSUE THREAD

**Issue by Seferan** [Sebaestschjin/gloomhaven-saveloader#35]
Might be a nice feature to do some sort of encoding or encryption on the Hidden Notes so they aren't showing in plain text in the save JSON.   Anything implemented will be easily decoded by a determined player, but would at least provide some protection against accidental observation.

**Comment by Sebaestschjin** [comment]
Yeah good point. Simple decoding should be enough for that (have to check whether there's already some library ready to use for that, like base64), as anyone with the save can easily read the hidden notes, even without knowledge of the encoding/encryption in place. He'd simply has to switch to all players. :-) But simpe encoding would prevent accidental reading.

**Comment by Sebaestschjin** [comment]
Another property that should be encoded is the personal quest. The simplest thing to do there is using the item card number. This information already exists in `game`.
