### ISSUE TITLE
Insufficient Wait during characters.setup for maxHP

### ISSUE THREAD

**Issue by Seferan** [Sebaestschjin/gloomhaven-saveloader#5]
On my current save, the maxHP routine is failing due to some component not being present.  The following change fixes it

FROM:
Wait.time(function() characters.setup_character_maxHP(player_zone, character) end, 1)  
TO
Wait.time(function() characters.setup_character_maxHP(player_zone, character) end, 5)

**Comment by Sebaestschjin** [comment]
I raised the wait for now. Ultimately I'd like to have a better waiting mechanism which conditions, where you can wait for specific tasks to finish. I'll redo that later.
