### ISSUE TITLE
Only place sheets that are provided in the save file

### ISSUE THREAD

**Issue by Seferan** [Sebaestschjin/gloomhaven-saveloader#52]
Retired Characters Sheet should not be loaded if there are no retired characters.   Technically this is supposed to be part of the "City Records" which is not unlocked until the first character retires.

**Comment by Sebaestschjin** [comment]
I'll extend the task to also reconsider the special unlock condition sheet. It should only be loaded, when the information is provided in the save file. Otherwise it should be ignored.
